version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DBNAME: banking

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: banking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"