# Use official MySQL image from Docker Hub
FROM mysql:latest

# Environment variables
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=banking
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=password

# Expose the MySQL port
EXPOSE 3306